apiVersion: v1
kind: Service
metadata:
  name: springboot-workflow
  namespace: namespace-workflow-1722392899130
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: springboot-workflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080